config/routes.rb
Rails.application.routes.draw do
  resources :products
  resource :cart, only: [:show] do
    collection do
      delete :reset
      post :checkout
    end
  end
  resources :cart_items, only: [:create, :update, :destroy] do
    member do
      post :increment
      post :decrement
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

  def calculate_total
    self.total_amount = cart_items.includes(:product).sum('quantity * products.price')
    save
  end

  def total_items
    cart_items.sum(:quantity)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :set_cart

  def set_cart
    @current_cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @current_cart = Cart.create
    session[:cart_id] = @current_cart.id
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    @cart_item = @current_cart.cart_items.find_or_initialize_by(product: product)
    if @cart_item.new_record?
      @cart_item.quantity = 1
    else
      @cart_item.quantity += 1
    end
    @cart_item.save
    @current_cart.calculate_total
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Product added to cart." }
      format.turbo_stream { render turbo_stream: turbo_stream.update("cart_items", partial: "cart_items", locals: { cart: @current_cart}) }
    end
  end

  def decrement
    @cart_item = @current_cart.cart_items.find(params[:id])
    if @cart_item.quantity == 1
      @cart_item_id = @cart_item.id
      @cart_item.destroy
    else
      @cart_item.quantity -= 1
      @cart_item.save
    end
    @current_cart.calculate_total
    respond_to do |format|
      format.html { redirect_to cart_path, notice: "Quantity updated" }
      format.turbo_stream { render "update_count", locals: { cart_item: @cart_item } }
    end
  end

  def increment
    @cart_item = @current_cart.cart_items.find(params[:id])
    @cart_item.quantity += 1
    @cart_item.save
    @current_cart.calculate_total
    respond_to do |format|
      format.html { redirect_to cart_path, notice: "Quantity updated" }
      format.turbo_stream { render "update_count", locals: { cart_item: @cart_item } }
    end
  end

  def destroy
    @cart_item = @current_cart.cart_items.find(params[:id])
    @cart_item.destroy
    @current_cart.calculate_total
    respond_to do |format|
      format.html { redirect_to cart_path, notice: "Product removed from cart." }
      format.turbo_stream { render "update_count", locals: { cart_item: @cart_item } }
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def reset
    @current_cart.cart_items.destroy_all
    @current_cart.update(total_amount: 0)
    redirect_to cart_path, notice: "Cart has been reset."
  end

  def checkout
    @current_cart.cart_items.destroy_all
    @current_cart.update(total_amount: 0)
    session[:cart_id] = nil
    redirect_to root_path, notice: "Thank you for your purchase!"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart_items/_cart_item_amount.html.erb
<%= cart_item.quantity %>

app/views/cart_items/_cart_items.html.erb
<div class="absolute flex items-center justify-center h-4 w-4 bg-green-400 rounded-full top-3 right-3"><%= cart.total_items %></div>

app/views/cart_items/update_count.turbo_stream.erb
<%= turbo_stream.update "cart_items" do %>
  <%= render "cart_items", cart: cart_item.cart %>
<% end %>

<% if cart_item.destroyed? %>
  <%= turbo_stream.remove "cart_item_#{cart_item.id}" %>
<% else %>
  <%= turbo_stream.update "cart_item_quantity#{cart_item.id}" do %>
    <%= render "cart_item_amount", cart_item: cart_item %>
  <% end %>
<% end %>

<%= turbo_stream.update "product_price_#{cart_item.id}" do %>
  <%= number_to_currency(cart_item.product.price * cart_item.quantity) %>
<% end %>

<%= turbo_stream.update "cart_total" do %>
  <%= number_to_currency(cart_item.cart.total_amount) %>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image, "Product Image", class: "block text-gray-700 font-bold mb-2" %>
    <%= form.file_field :image, required: true, class: "w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="flex flex-row gap-1">
  <div>
    <%= image_tag product.image if product.image.attached? %>
  </div>
  <div id="<%= dom_id product %>" class="flex flex-row items-center justify-between grow">
    <p class="my-5">
      <%= product.name %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Price:</strong>
      <%= product.price %>
    </p>

  </div>
</div>

app/views/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Products" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="products" class="min-w-full">
    <% @products.each do |product| %>
      <div class="m-1">
        <%= render product %>
      </div>
      <p>
        <%= button_to "Add to Cart", cart_items_path(product_id: product.id), method: :post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", @product, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>